### ISSUE TITLE
Custom Icons and missing plus icons

### ISSUE THREAD

**Issue by roderickn-wt** [FacilMap/Leaflet.DraggableLines#1]
Hello, 

I imported Leaflet.DraggableLines via the NPM, overall is working good but the plusIcons are not appearing. I have used the default settings with no luck , even manually set `allowExtendingLine` to true and nothings changed. Any idea what might cause this or ways to debug it? I can't seem to find any empty markers on the map that would the plusIcons.

Another question, I am just wondering if there is a way to use custom icons for the markers? I have looked through the code and have not noticed an possible option. 

Thank you in advance for any assistance you can provide.

Roderick

**Comment by cdauth** [comment]
Do the plus icons appear for you on the [demo](https://unpkg.com/leaflet-draggable-lines/example.html)?

You can customize the icons using the `*MarkerOptions` options. Here is an example:
```typescript
new DraggableLines(map, {
	tempMarkerOptions: () => ({
		icon: L.icon({
			iconUrl: 'tempMarker.svg',
			iconSize: [12, 20],
			iconAnchor: [6, 20],
			popupAnchor: [0, -20]
		});
	})
}).enable();
```

**Comment by roderickn-wt** [comment]
They do appear in the demo, and in the modified demo that I used to test some of the custom options, but not when I implemented it in the my project. Every other part of what I tested and tried seems to be work as I tested but the plusIcon. This is the test work that I did in prep from the work in the project. I will say that the project is an Angular project, but being that leaflet is working as while as the other parts of Draggablelines except the plusIcons doesn't feel like Angular is the issue.
[L.HighlightableLayers.html.zip](https://github.com/FacilMap/Leaflet.DraggableLines/files/8402642/L.HighlightableLayers.html.zip)

thank you for the Icon suggestion.

**Comment by cdauth** [comment]
In the example that you have sent the plus icon appears for me. If I understand you correctly, it appears for you as well, but it fails in your Angular project? Can you share some of the code from your Angular project?

**Comment by roderickn-wt** [comment]
this is where I set up DraggableLines:
this._draggable = new DraggableLines(_mapService.map,  {
              plusMarkerOptions: (layer, isStart) => {
                return isStart ? {opacity: 0, interactive: false} : {};
              },
              dragMarkerOptions: (layer, i, length) => {
                return i === 0 ? {opacity: 0, interactive: false} : {};
              },
              plusTempMarkerOptions: (layer, isStart) => {
                return isStart ? {opacity: 0, interactive: false} : {};
              }
            } as DraggableLinesHandlerOptions);

and where I create the polyline:
`this._newPath = new Polyline([start, end], { color: '#3388ff', weight: 3 });
    this._newPath.addTo(this._mapService.map);
    this._draggable.enableForLayer(this._newPath);`

if there is nothing there, I will try to set up a sandbox later today and try that way.

**Comment by cdauth** [comment]
I don't see any obvious mistakes that would explain the problem.

Unrelated to the problem, I'm wondering why you need the type cast to `DraggableLinesHandlerOptions`? Also, if you enable the layer manually using `enableForLayer()`, you should probably set the `enableForLayer: false` option on `DraggableLines` to prevent it from being enabled automatically.

**Comment by cdauth** [comment]
Are you using the most recent version of Leaflet?

**Comment by roderickn-wt** [comment]
I am using the latest version of leaflet, 1.7.0. 

I will add that to the options, and as for the type casting, I did that cause the IDE kept telling me that `plusMarkerOptions` was not being used. I had the same issue with or without, just have not removed it.

**Comment by cdauth** [comment]
That's weird, which IDE are you using?

**Comment by roderickn-wt** [comment]
WebStorm

**Comment by roderickn-wt** [comment]
I made a sand box with a simple leaflet map and draggablelines, it is working fine. https://stackblitz.com/edit/angular-ivy-d1bxsx?file=src/index.html

**Comment by cdauth** [comment]
Closing this as it does not seem to be reproducible. If you manage to get a reproducible demo running, feel free to reopen this.
