### ISSUE TITLE
Issue: dragging new point on line causes repetitive point additions

### ISSUE THREAD

**Issue by wisc-gmv** [FacilMap/Leaflet.DraggableLines#10]
View [this stackblitz](https://stackblitz.com/edit/react-f62lku?file=src%2FRoutePolyline.js) and drag from the line between two consecutive green markers. 

This bug occurs: (see image)
![image](https://github.com/user-attachments/assets/6526de19-958e-450f-8a1f-6ba4b45e04e0)

If the user moves a marker above or below the segment that has issues, the problem seems to be resolved. If you listen to `dragstart drag dragend`, the `idx` is always `NaN`.

**Comment by cdauth** [comment]
Very interesting! It seems like the problem occurs when a segment of the line is exactly vertical. I have released v3.2.1, which should fix the problem.

**Comment by wisc-gmv** [comment]
@cdauth I thought it was an interesting one as well. I appreciate the patch! Thanks for this awesome extension and for working on submitted issues.
