### ISSUE TITLE
Larger routes cause significant lag

### ISSUE THREAD

**Issue by viamatt** [FacilMap/Leaflet.DraggableLines#6]
I'm using DraggableLines as part of a routing website using a routing engine to snap to roads, even routes of 150-200KM can end up with 2-300 Route Points and 1000+ LatLngs, longer trips can have 5000+ LatLngs.   This causes performance to drop off massively when moving the mouse over a line.  Is there any way to improve performance, eg only perform a scan over the visible section of the map, limit the max zoom level draggable events trigger at etc?

I've attached a call stack of a mousemove event firing to show the slowness on a route with 1029 LatLngs and 334 handles covering 208kM.

![image](https://github.com/FacilMap/Leaflet.DraggableLines/assets/4027673/e78f2b81-0687-483b-a0de-cabe4b488cec)

**Comment by cdauth** [comment]
Quite interesting. Could you maybe share an example array of route points and LatLngs that I could reproduce the issue with? Then I could experiment with it and see if I can manage to improve the performance.

**Comment by viamatt** [comment]
Thanks, I've attached a couple of json files, handles.json contains the 334 draggable points and track.json contains the route as output from the routing engine with 5130 points, there are passed in to setDraggableLinesRoutePoints and setLatLngs respectively.

[track.json](https://github.com/FacilMap/Leaflet.DraggableLines/files/15062522/track.json)
[handles.json](https://github.com/FacilMap/Leaflet.DraggableLines/files/15062523/handles.json)

**Comment by viamatt** [comment]
Thank you, there are VERY SIGNIFICANT speed improvements on V3.0.0 :)
