### ISSUE TITLE
Default markers are all black

### ISSUE THREAD

**Issue by thomthom** [FacilMap/Leaflet.DraggableLines#7]
The docs for `dragMarkerOptions` says:

> By default, returns a green marker for the first line point, a red marker for the last one and a blue marker for all other line points. By default, the marker is on the marker pane behind all other markers.

I'm just seeing a black marker for all default markers. Even on the Demo page.

Is the docs out of date, is is there a bug in the defaults?

**Comment by cdauth** [comment]
Quite interesting, this must have been broken for a while, I guess I changed something at some point and didn't remember that they used to have colours.

I have published v3.0.1 now that should have the colours again.

**Comment by thomthom** [comment]
Ah, I was coming back here to post my findings, I'd poked around at the icons generated and found that the color variables had not expanded. Thank you for the quick fix.

Btw, would you accept a PR to export the `createIcon` utility? Seems convenient in order to quickly create additional icons similar to the default.

**Comment by cdauth** [comment]
I've changed the code to export the icon functionality. Could you have a look if this fits your use case? Then I would make another release.

**Comment by thomthom** [comment]
Yes, that looks great. Makes it very convenient to create multiple marker types without having to create your own icon. Thank you very much! 👍

**Comment by cdauth** [comment]
Okay, I've release v3.0.2.
