### ISSUE TITLE
Feature request idea: rectangles

### ISSUE THREAD

**Issue by nonsintetic** [FacilMap/Leaflet.DraggableLines#8]
It would be nice for the Rectangles to only have 2 handles, or some other way for them to remain rectangular while dragging. Awesome plugin, really saved my bacon.

**Comment by cdauth** [comment]
This is really interesting, I was not aware that `L.Rectangle` was a sub-class of `L.Polygon` so dragging was enabled for it. In fact, dragging it was much more broken than just not keeping the it rectangular.

I have updated the behaviour for rectangles to enforce keeping them rectangular. Their behaviour is now also documented in the README. I have released version 3.1.0 with the changes.
