### ISSUE TITLE
Feature request: disable creating new points on click

### ISSUE THREAD

**Issue by nonsintetic** [FacilMap/Leaflet.DraggableLines#9]
There a way to prevent extending the line at the ends, but there doesn't seem to be a way to prevent the creation of new points when clicking inside the polylines. 

This would be useful if you just want to use the object as a line, not a polyline.

**Comment by cdauth** [comment]
Good suggestion! I have added an option `allowDraggingLine` for this and released version 3.2.0 to include it.
